spring.application.name=reve

spring.profiles.active=dev

server.port=8080

spring.thymeleaf.cache=false

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

server.error.whitelabel.enabled=false
server.error.path=/error
